"""initial schema

Revision ID: bc011872e3ef
Revises: 
Create Date: 2026-09-14 21:29:36.504432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc011872e3ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_conversions_occurred_at'), 'conversions', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_conversions_user_id'), 'conversions', ['user_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_received', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_ingested', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_quarantined', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ad_spend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'date', name='uq_ad_spend_campaign_date')
    )
    op.create_index(op.f('ix_ad_spend_campaign_id'), 'ad_spend', ['campaign_id'], unique=False)
    op.create_table('quarantined_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_reason', sa.Text(), nullable=False),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quarantined_records_ingestion_run_id'), 'quarantined_records', ['ingestion_run_id'], unique=False)
    op.create_table('touchpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('touch_type', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_touchpoints_campaign_id'), 'touchpoints', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_touchpoints_occurred_at'), 'touchpoints', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_touchpoints_user_id'), 'touchpoints', ['user_id'], unique=False)
    op.create_table('attribution_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversion_id', sa.Integer(), nullable=False),
    sa.Column('touchpoint_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('credit', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('attributed_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversions.id'], ),
    sa.ForeignKeyConstraint(['touchpoint_id'], ['touchpoints.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversion_id', 'touchpoint_id', 'model_name', name='uq_attribution_conversion_touchpoint_model')
    )
    op.create_index(op.f('ix_attribution_results_conversion_id'), 'attribution_results', ['conversion_id'], unique=False)
    op.create_index(op.f('ix_attribution_results_model_name'), 'attribution_results', ['model_name'], unique=False)
    op.create_index(op.f('ix_attribution_results_touchpoint_id'), 'attribution_results', ['touchpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attribution_results_touchpoint_id'), table_name='attribution_results')
    op.drop_index(op.f('ix_attribution_results_model_name'), table_name='attribution_results')
    op.drop_index(op.f('ix_attribution_results_conversion_id'), table_name='attribution_results')
    op.drop_table('attribution_results')
    op.drop_index(op.f('ix_touchpoints_user_id'), table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_occurred_at'), table_name='touchpoints')
    op.drop_index(op.f('ix_touchpoints_campaign_id'), table_name='touchpoints')
    op.drop_table('touchpoints')
    op.drop_index(op.f('ix_quarantined_records_ingestion_run_id'), table_name='quarantined_records')
    op.drop_table('quarantined_records')
    op.drop_index(op.f('ix_ad_spend_campaign_id'), table_name='ad_spend')
    op.drop_table('ad_spend')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_conversions_user_id'), table_name='conversions')
    op.drop_index(op.f('ix_conversions_occurred_at'), table_name='conversions')
    op.drop_table('conversions')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
